### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by CharlieAtlas** [OpenTTD/wiki-data#16]
[Content Service](https://wiki.openttd.org/en/Archive/Community/Content%20Service)

This page has some broken links on it in the signing up for an account section.  I tried to figure out what they were, but i feel like i don't know enough history to tell exactly what they should be pointing to.  That section might just need to be re-written if I understand it correctly.  

This page might need to be unarchived as well, as the [Online Content](https://wiki.openttd.org/en/Manual/Online%20content) points to it.

**Comment by TrueBrain** [comment]
Please fix the things you think are needed on our wiki. It is a community wiki after all :) I do not think you will get any reply here, as this repository is merely the database backend for our wiki. Not meant to collaborate. Sorry :(
