### ISSUE TITLE
anchor link and accent

### ISSUE THREAD

**Issue by Rivarossi** [OpenTTD/wiki-data#20]
Hi, in the wiki the anchor links don't work with accented characters (e. g. : à, è...). I'm workings at the Italian wiki and in our language the accented vowels are often used. Is there the possibility to fix this problem? Thx

**Comment by TrueBrain** [comment]
Do you have an example URL for this? Or an example? That would greatly help understanding what you mean ;)

**Comment by Rivarossi** [comment]
[example]([[it/Manuale/Settaggi/Localizzazione#Unità-di-velocità|''unità di velocità'']])

**Comment by TrueBrain** [comment]
Thank you!

Anchors have to be "slugified", in order for all browsers to process them correctly. This means they need to be `a-z`, and not have any accents etc on them. This is why all anchors have a link next to them you can copy, to use in your links.

I see you did replace spaces with `-`. But it would be better to just copy them from the anchor, and use that in your links. That is the best way to use them, and avoids the problem you are running into.

Does this help you?

**Comment by Rivarossi** [comment]
Ok, no problem. I'm used to wikipedia (IT) where you can write the anchors without "slugify". I was asking if it was possible to fix the problem because many languages use accented characters and it would make the work a lot easier for the translators who will have to face the same problem in the future.

**Comment by TrueBrain** [comment]
I rather avoid doing that as parsing URLs is a world of hurt, and rather error prune. Mediawiki has a long history of bugs in that department .. if possible, I rather avoid that :D

So for now, I am not willing to implement that feature. But I will keep it in the back of my head if similar questions and/or problems arise :)

Despite that, always feel free to request these kind of features; so if you have any other, do let us know! Cheers!
