### ISSUE TITLE
Move/rename page 'en/Archive/Compiling on GNU∕Linux and 🟉BSD'

### ISSUE THREAD

**Issue by Bouke** [OpenTTD/wiki-data#25]
There is an unsupported (on my machine) unicode symbol used on the following page. The character should display an asterisk, but doesn't and shows up as either a black square or squiggly lines. Suggestion to drop the asterisk or pick a different unicode symbol.

| current title                                   | new title                                       |
| ----------------------------------------------- | ----------------------------------------------- |
| `en/Archive/Compiling on GNU∕Linux and 🟉BSD` | `en/Archive/Compiling on GNU∕Linux and BSD`

**Comment by PeterN** [comment]
It's an old archive, the information is out of date and better served by https://github.com/OpenTTD/OpenTTD/blob/master/COMPILING.md

If this really needs to be touched, it should just be deleted.

**Comment by TrueBrain** [comment]
As this is a wiki, please feel free to make any corrections on the wiki. Just login, and make any changes you feel necessary.

> Suggestion to drop the asterisk or pick a different unicode symbol.

The only thing that solution causes, is that someone else complaints they don't have that codepoint :) As it goes with anything outside ASCII .. some fonts do have them, some don't. The codepoints used here are rendered properly on Windows, so I guess the current solution covers 90% of our users. So when you pick something new, please keep that in mind.

Either way, single page renames should be done via the wiki itself :) Cheers!
