### ISSUE TITLE
Wiki may have incorrectly-named links.

### ISSUE THREAD

**Issue by kevinfields777** [OpenTTD/wiki-data#26]
Moving this over here from https://github.com/OpenTTD/OpenTTD/issues/11257

Summary - it looks like some links to external pages have a placeholder "None" for the name, I'm assuming this happened when moving from wikimedia to truewiki.  

For a solution? If someone can use some magic code to find all the external links named "None", I'd be happy to go through and hand edit all the pages.

**Comment by TrueBrain** [comment]
Never actually sure if people are just lazy, or just don't know how searches work :D Hihi, sorry, hard to judge, but I will give you the benefit of the doubt, as I know you a bit longer :)

On the top of this page is a large `search` input box; you can throw anything in there you like. So if you want to know all instances of a link title ending on `None`, just search for it. `None` is giving a lot of unrelated hits, but `" None]"` seems to works nicely!

Help a man to fish :)

**Comment by kevinfields777** [comment]
Super-helpful reply, thank you! new skill unlocked!   

Link for me to jump into this later. https://github.com/search?q=repo%3AOpenTTD%2Fwiki-data%20%22%20None%5D%22&type=code

**Comment by TrueBrain** [comment]
Question asked and answered. Closing this up, assuming you either addressed the issues or lost interest :)
