### ISSUE TITLE
Cannot upload new image

### ISSUE THREAD

**Issue by kevinfields777** [OpenTTD/wiki-data#31]
Working on the Cindini scenario to add new content. 
https://wiki.openttd.org/en/Community/Scenarios/Cindini

I've added this file link: [File:en/Community/Scenarios/Cindini/cindinilogo.png](https://wiki.openttd.org/File/en/Community/Scenarios/Cindini/cindinilogo.png)

I click on it to upload them image. I add the image, click Save. I get taken to a Cloudflare page to verify that I'm human, I pass, and then get an error page "404:NotFound".  

Am I doing something wrong?

**Comment by TrueBrain** [comment]
Okay, so there was a combination of issues going on.

First of, Cloudflare was caching pages for image files, where it shouldn't. In result, you could see a page as the wrong user etc. (there was no security implications; the GET could just be cached. POST was always revalidated).
This caching layer is now disabled.

Second, Cloudflare WAF was triggering like a mad-man on the upload of an image. It seems it ticked every OWASP rule there is. Things like: there is a `\0` in the content. Like, yeah, I know, it is an image. Either way, when you pass the Cloudflare validation, it rePOSTs the page, but with a very odd and non-sensible content. In return, the wiki-server went: I am not sure what you are smoking, but get out of here.
I tuned the WAF settings to let these kind of POSTs through.

You should now be able to upload images again!
