### ISSUE TITLE
.JPG file support requested

### ISSUE THREAD

**Issue by kevinfields777** [OpenTTD/wiki-data#32]
Trying to upload an image with .jpg extension results in this error: 

File namespace should end with either ".png", ".gif", or ".jpeg" 

The .jpg extension should also be recognized as valid.

**Comment by TrueBrain** [comment]
Luckily the path to resolvement is pretty clear :) just rename the extension and you are good to go!

Moving this to the TrueWiki repository.

**Comment by TrueBrain** [comment]
Scratch that, you cannot move tickets cross organisation. Mind opening a ticket on https://github.com/TrueBrain/TrueWiki ?

In general, this repository is only containing the data. Please report issues in TrueWiki if they are related to the underlying software. Tnx :)
