### ISSUE TITLE
Ludde's page has Manual written instead of OpenTTD

### ISSUE THREAD

**Issue by Saver310** [OpenTTD/wiki-data#34]
[https://wiki.openttd.org/en/Archive/Community/Users/Ludde](url)

**Comment by TrueBrain** [comment]
![image](https://github.com/user-attachments/assets/ecea8bcc-8f04-4f00-b277-102d782dbfee)

Please use the wiki for edits; not this issue tracker. On the top right corner on the wiki you can login, and after that edit the page yourself.

It is almost like it is a wiki ;)
