### ISSUE TITLE
Add extra image example to Basic 3-Way page 

### ISSUE THREAD

**Issue by botanist75** [OpenTTD/wiki-data#40]
Hi, 

I noticed that there wasn't a second image on the [Basic 3-Way](https://wiki.openttd.org/en/Community/Junctionary/Basic%203-Way) page to account for (what I believe to be) the alternate way to construct a 3-way junction. (Also the old example uses block signals instead of path signals.)

I have created a new image to add to the page:

![3way-basic3-alt](https://github.com/user-attachments/assets/e68685ef-b74b-4626-8bc5-b51600dc77b1)

Please add this to the article, I would appreciate it :D . (I tried to add it myself, and then with a PR, but was unable to.)

**Comment by TrueBrain** [comment]
These kind of edits should be done on the wiki itself, and we do not accept PRs for such changes.

If you have trouble making edits to the wiki, please join our Discord and ask in #openttd-help for support.
