### ISSUE TITLE
Compiling on Windows using MSYS2 page is out of date

### ISSUE THREAD

**Issue by brianpefisk** [OpenTTD/wiki-data#42]
Compiling on Windows using MSYS2 page is out of date. There are two problems I have discovered so far

1. You also neeed to download "pactoys" using pacman
2. the make step doesn't work ( cmake .. -G "MSYS Makefiles" )
CMake Error: Could not create named generator MSYS Makefiles - I haven't yet resolved this 

https://stackoverflow.com/questions/37365355/cmake-msys-makefiles-generator-missing

may provide a clue

**Comment by brianpefisk** [comment]
for step 2 don't install cmake install mingw-w64-x86_64-cmake instead (for x64) 
then use the command ${MINGW_PREFIX}/bin/cmake .. -G "MSYS Makefiles"

doing that I successfully built the game :-)

**Comment by LordAro** [comment]
If you want to make edits on the wiki, make the edits on the wiki!
